from . import list_of_my_bots
from . import detail_information_about_bot
from . import requests_button
from . import rassilka_button
from . import priyem
from . import order_requests
from . import delete_button
from . import captcha_button
from . import set_captcha_button
from . import captcha_button_off